#
# Sharepoint related initialization
#
$siteURL = $null
$WSuri = $null

$CurrentFSN = $null
$CurrentACK = $null
$RunningState = $null
$StateTableID = $null 

$TruSPList = $null
$StateTable = $null
$FeedAckTable = $null
$RecordSentTable = $null
$RecordReceiveTable = $null

$NotVert = ".\TRU\notprocessed\verification"
$NotAck = ".\TRU\notprocessed\verify_ack"
$Vert = ".\TRU\processed\verification"
$Ack = ".\TRU\processed\verify_ack"
$ErrVert = ".\TRU\error\verification"
$ErrAck = ".\TRU\error\verify_ack"
$TempDir = ".\TRU\temp"
$CurrentACKFile = $null
$MailRelay = "smtp.   "
$MailSender = "TRU-EDI@"
$MailRecipient = "patrick.law@"
$Logfile = ".\TRU\__logfile.txt"
$SendLog = $true

$CodeDesc = @{"000"="VERIFICATION SUCCESS";
"001"="ERR - ITEM IS MISSING OR INVALID"; 
"002"="ERR - UPC IS MISSING OR INVALID";
"003"="ERR - ITEM UID IS INVALID";
"004"="ERR - CASE LENGTH IS MISSING OR INVALID";
"005"="ERR - CASE WIDTH IS MISSING OR INVALID";
"006"="ERR - CASE HEIGHT IS MISSING OR INVALID";
"007"="ERR - CASE VOLUME IS MISSING OR INVALID";
"008"="ERR - UNIT LENGTH IS MISSING OR INVALID";
"009"="ERR - UNIT WIDTH IS MISSING OR INVALID";
"010"="ERR - UNIT HEIGHT IS MISSING OR INVALID";
"011"="ERR - UNIT VOLUME LENGTH IS MISSING OR INVALID";
"012"="ERR - DESCRIPTION IS MISSING";
"013"="ERR - MASTER PACK QUANTITY IS MISSING OR INVALID";
"014"="ERR - INNER PACK QUANTITY IS MISSING OR INVALID";
"015"="ERR - UNIT EXEMPT FLAG IS MISSING OR INVALID";
"016"="ERR - CASE WEIGHT IS MISSING OR INVALID";
"017"="ERR - ITEM WEIGHT IS MISSING OR INVALID";
"018"="ERR - BATTERY TYPE 1 IS INVALID";
"019"="ERR - BATTERY QTY 1 IS INVALID";
"020"="ERR - BATTERY TYPE 2 IS INVALID";
"021"="ERR - BATTERY QTY 2 IS INVALID";
"022"="ERR - BATTERY TYPE 3 IS INVALID";
"023"="ERR - BATTERY QTY 3 IS INVALID";
"024"="CODE UNASSIGNED";
"025"="ERR - BATTERY REQUIRED IS INVALID";
"026"="ERR - BATTERY INCLUDED IS INVALID";
"027"="ERR - SAMPLE RECEIVED DATE IS MISSING OR INVALID";
"028"="ERR - SAMPLE VERIFIED DATE IS INVALID";
"029"="ERR - ITEM IS ALREADY VERIFIED";
"100"="OUT OF SEQUENCE ERROR";
"101"="INCORRECT RECORD COUNT";
"102"="HEADER RECORD IS MISSING";
"103"="TRAILER RECORD IS MISSING";
"999"="ERR - MULTIPLE ERRORS ON ITEM RECORD"
"1000"="WAITING FOR ACKNOWLEGEMENT"}

$ReceiveRecordDesc = @{"0" = "PROCESS SUCCESSFULLY";
"1" = "ERR - NOT UPDATED, ITEM WAS NOT SENT FOR VERIFICATION RECENTLY";
"2" = "ERR - ITEM WAS NOT FOUND IN VERIFICATION LIST"}

$StateErrDesc = @{"-1" = "ACKNOWLEDGE FILE OUT OF SEQUENCE ERROR";
"-2" = "ACKNOWLEDGE FILE HEADER ERROR";
"-3" = "ACKNOWLEDGE FILE RECORD ITEM ERROR";
"-4" = "ACKNOWLEDGE FILE TRAILER ERROR";
"-5" = "FEED FILE OUT OF SEQUENCE ERROR";
"-6" = "FEED FILE INCORRECT RECORD COUNT";
"-7" = "FEED FILE HEADER RECORD MISSING";
"-8" = "FEED FILE TRAILER RECORD MISSING"}
